/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Answer } from "./interfaces/Answer";
export namespace Components {
    interface QuestionAnswer {
    }
    interface TrashData {
    }
}
declare global {
    interface HTMLQuestionAnswerElement extends Components.QuestionAnswer, HTMLStencilElement {
    }
    var HTMLQuestionAnswerElement: {
        prototype: HTMLQuestionAnswerElement;
        new (): HTMLQuestionAnswerElement;
    };
    interface HTMLTrashDataElement extends Components.TrashData, HTMLStencilElement {
    }
    var HTMLTrashDataElement: {
        prototype: HTMLTrashDataElement;
        new (): HTMLTrashDataElement;
    };
    interface HTMLElementTagNameMap {
        "question-answer": HTMLQuestionAnswerElement;
        "trash-data": HTMLTrashDataElement;
    }
}
declare namespace LocalJSX {
    interface QuestionAnswer {
    }
    interface TrashData {
        "onAnswerReceived"?: (event: CustomEvent<Answer>) => void;
        "onReset"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "question-answer": QuestionAnswer;
        "trash-data": TrashData;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "question-answer": LocalJSX.QuestionAnswer & JSXBase.HTMLAttributes<HTMLQuestionAnswerElement>;
            "trash-data": LocalJSX.TrashData & JSXBase.HTMLAttributes<HTMLTrashDataElement>;
        }
    }
}
